import { state } from "../core/state.js";
import { importNewMatches } from "../services/matchImportService.js";
import {
  describeLobbyAge,
  fetchLiveLobbies
} from "../services/matchesService.js";
import { resolveLobbies } from "../services/aoeApi.js";
import { toast } from "../ui/toast.js";

// lobby.json is regenerated by the fetch-lobby workflow roughly every 5-15
// minutes, so polling faster than that only re-reads the same file.
const POLL_INTERVAL_MS = 60 * 1000;

// How many recognised community members must share a lobby before it is
// treated as a community game.
const MIN_COMMUNITY_IN_LOBBY = 2;

let pollTimer = null;

export function initLivePage() {
  const button = document.getElementById("livePollNowBtn");
  if (!button) return;

  button.addEventListener("click", () => poll(true));

  // Re-render when player identities arrive, so names resolve on first load.
  window.addEventListener("lotr:dataChanged", () => {
    if (lastLobbyData) render(lastLobbyData);
  });

  poll(false);
  if (!pollTimer) {
    pollTimer = window.setInterval(() => poll(false), POLL_INTERVAL_MS);
  }
}

let lastLobbyData = null;

async function poll(manual) {
  const button = document.getElementById("livePollNowBtn");
  const status = document.getElementById("liveStatus");
  if (button) button.disabled = true;

  try {
    const [data, importResult] = await Promise.all([
      fetchLiveLobbies(),
      importNewMatches().catch(error => {
        // A failed import must not hide live lobby data.
        console.warn("[live] import failed", error);
        return { added: 0 };
      })
    ]);

    lastLobbyData = data;
    const lobbies = render(data);
    const imported = importResult?.added
      ? ` · ${importResult.added} new match${importResult.added === 1 ? "" : "es"} recorded`
      : "";

    if (status) {
      // Say how old the underlying data is, not just when we last re-read the
      // file: the file itself only changes every ~5-15 minutes.
      status.textContent =
        `${lobbies.length} LOTR lobb${lobbies.length === 1 ? "y" : "ies"} open · ` +
        `feed ${describeLobbyAge(data.lastModified, data.isLive)}` +
        imported;
    }
  } catch (error) {
    console.error(error);
    if (status) {
      status.textContent =
        `Could not read the lobby feed. Last tried: ${new Date().toLocaleTimeString()}`;
    }
    if (manual) toast("Failed to check live match data", "err");
  } finally {
    if (button) button.disabled = false;
  }
}

// Returns the community lobbies it rendered.
function render(data) {
  const idle = document.getElementById("liveIdle");
  const lobbyPanel = document.getElementById("liveLobby");

  // Shared with the Balance page's "Select from lobby" button, so both agree on
  // which lobby is the community game and who is in it.
  const { lobbies: annotated, community, best } = resolveLobbies(
    data,
    state.playerDatasets.original?.length
      ? state.playerDatasets.original
      : state.players || [],
    MIN_COMMUNITY_IN_LOBBY
  );

  if (!best) {
    if (idle) {
      idle.hidden = false;
      const detail = idle.querySelector("[data-live-detail]");
      if (detail) {
        detail.textContent = annotated.length
          ? `${annotated.length} LOTR lobb${annotated.length === 1 ? "y is" : "ies are"} open, but no ${MIN_COMMUNITY_IN_LOBBY}+ community members are in one yet.`
          : "No LOTR, BFME, or Hobbit lobbies are open right now.";
      }
    }
    if (lobbyPanel) lobbyPanel.hidden = true;
    return annotated;
  }

  if (idle) idle.hidden = true;
  if (lobbyPanel) lobbyPanel.hidden = false;

  const name = document.getElementById("lobbyName");
  const info = document.getElementById("lobbyInfo");
  const teams = document.getElementById("lobbyTeams");

  if (name) name.textContent = best.description || "LOTR lobby";
  if (info) {
    info.textContent =
      `${best.communityMembers.length} community member${best.communityMembers.length === 1 ? "" : "s"} ` +
      `of ${best.memberCount} in lobby` +
      (best.maxplayers ? ` (max ${best.maxplayers})` : "");
  }
  if (teams) teams.innerHTML = renderRoster(best);

  // Hand the recognised players straight to the balancer.
  const balanceBtn = document.getElementById("lobbyBalanceBtn");
  if (balanceBtn) {
    const ids = best.communityMembers
      .map(member => member.player?.id)
      .filter(Boolean)
      .slice(0, 8);
    balanceBtn.disabled = ids.length < 2;
    balanceBtn.onclick = () => {
      location.href = `./balance.html?players=${encodeURIComponent(ids.join(","))}`;
    };
  }

  renderOtherLobbies(community.slice(1));
  return annotated;
}

function renderRoster(lobby) {
  const rows = lobby.members
    .slice()
    .sort((a, b) => Number(b.isCommunity) - Number(a.isCommunity))
    .map(member => {
      const label = member.player
        ? `<a class="player-link" href="./profile.html?playerId=${encodeURIComponent(member.player.id)}">${escapeHtml(member.name)}</a>`
        : escapeHtml(member.name);
      const tag = member.isCommunity
        ? `<span class="muted small">community</span>`
        : `<span class="muted small">guest</span>`;
      return `<div class="assignment-row"><span>${label}</span>${tag}</div>`;
    })
    .join("");

  return `
    <section class="team">
      <h3>In lobby (${lobby.memberCount})</h3>
      ${rows || `<p class="muted">No players listed.</p>`}
    </section>
  `;
}

function renderOtherLobbies(others) {
  const container = document.getElementById("lobbyOdds");
  if (!container) return;

  if (!others.length) {
    container.innerHTML = "";
    return;
  }

  container.innerHTML = `
    <section class="card">
      <h3>Other community lobbies</h3>
      <div class="stats-list">
        ${others.map(lobby => `
          <div class="stats-list-row">
            <span>${escapeHtml(lobby.description || "LOTR lobby")}</span>
            <strong>${lobby.communityMembers.length}/${lobby.memberCount}</strong>
          </div>
        `).join("")}
      </div>
    </section>
  `;
}

function escapeHtml(value) {
  return String(value ?? "").replace(/[&<>"']/g, char => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;"
  }[char]));
}
